name: Auto-Deploy to AKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_TOKEN }}
        # This uses your token instead of service principal
    
    - name: Build and push
      run: |
        docker build --platform linux/amd64 -t pythonregistry2024.azurecr.io/python-devops-app:${{ github.sha }} .
        docker push pythonregistry2024.azurecr.io/python-devops-app:${{ github.sha }}
    
    - name: Deploy to AKS
      run: |
        az aks get-credentials -g devops-rg -n devops-cluster
        kubectl set image deployment/python-app python-app=pythonregistry2024.azurecr.io/python-devops-app:${{ github.sha }}
        kubectl rollout status deployment/python-app